import {
  Aprendente,
  Anamnese,
  Sessao,
  RegistroEvolucaoDominio,
  AvaliacaoPsicopedagogica,
  RelatorioPsicopedagogico,
  ModeloFormulario,
  LembreteConsulta,
  ConfiguracoesApp
} from '@/types';

export const CONFIGURACOES_PADRAO: ConfiguracoesApp = {
  tema: 'sistema',
  tamanhoFonte: 'padrao',
  notificacoesAtivas: false,
  somAtivo: true,
  volume: 75,
  vibracaoAtiva: true,
  somEscolhido: 'suave_cristal',
  alertasEmSegundoPlano: true,
  ocultarCamposVaziosImpressao: true,
  incluirSumarioRelatorio: true,
};

export const MOCK_APRENDENTES: Aprendente[] = [
  {
    id: 'apr-1',
    codigoInterno: 'AP-2026-001',
    nomeCompleto: 'Helena Duarte Ribeiro',
    dataNascimento: '2019-04-12',
    idadeCalculada: 7,
    pronome: 'Ela/Dela',
    contatoPreferencial: '(11) 98765-4321',
    cidadeUf: 'São Paulo/SP',
    status: 'avaliacao',
    paisResponsaveis: [
      {
        id: 'resp-1',
        nomeCompleto: 'Mariana Duarte Ribeiro',
        parentesco: 'Mãe',
        responsavelLegal: true,
        telefone: '(11) 98765-4321',
        email: 'mariana.duarte.demo@exemplo.com.br',
        melhorContato: 'WhatsApp no período da tarde (14h às 17h)',
        autorizacaoConsentimento: {
          status: 'autorizado',
          dataAutorizacao: '2026-02-10',
          observacao: 'Termo de consentimento demonstrativo assinado digitalmente na anamnese.',
        },
      },
      {
        id: 'resp-2',
        nomeCompleto: 'Carlos Eduardo Ribeiro',
        parentesco: 'Pai',
        responsavelLegal: true,
        telefone: '(11) 97654-3210',
        email: 'carlos.ribeiro.demo@exemplo.com.br',
        melhorContato: 'E-mail ou ligação após 18h',
        autorizacaoConsentimento: {
          status: 'autorizado',
          dataAutorizacao: '2026-02-10',
          observacao: 'Ciente da realização do processo de avaliação psicopedagógica.',
        },
      },
    ],
    contextoEscolar: {
      instituicao: 'Colégio Veredas da Serra (Demonstrativo)',
      etapaAno: '2º ano do Ensino Fundamental I',
      turno: 'Matutino',
      contatoEscolar: 'Profª Tatiana (Coordenação Pedagógica)',
      demandasEscolares: 'A escola relatou hesitação no processo de alfabetização formal, dispersão em tarefas com enunciados extensos e recusa em registrar respostas escritas.',
      adaptacoesApoios: 'Assento próximo à professora; apoio de fichas com apoio visual; divisão de atividades em blocos menores.',
    },
    notasInternas: 'Acolhimento caloroso demonstrado pela família. Helena expressa grande interesse por desenho e animais.',
    criadoEm: '2026-02-05',
    atualizadoEm: '2026-03-24',
  },
  {
    id: 'apr-2',
    codigoInterno: 'AP-2025-042',
    nomeCompleto: 'Lucas Mendes Vasconcelos',
    dataNascimento: '2013-08-20',
    idadeCalculada: 13,
    pronome: 'Ele/Dele',
    contatoPreferencial: '(21) 99123-4567',
    cidadeUf: 'Rio de Janeiro/RJ',
    status: 'acompanhamento',
    paisResponsaveis: [
      {
        id: 'resp-3',
        nomeCompleto: 'Patrícia Mendes Vasconcelos',
        parentesco: 'Mãe',
        responsavelLegal: true,
        telefone: '(21) 99123-4567',
        email: 'patricia.mendes.demo@exemplo.com.br',
        melhorContato: 'Telefone comercial pela manhã',
        autorizacaoConsentimento: {
          status: 'autorizado',
          dataAutorizacao: '2025-08-15',
          observacao: 'Autorização renovada para o ciclo de acompanhamento 2026.',
        },
      },
    ],
    contextoEscolar: {
      instituicao: 'Escola Parque Integrada (Demonstrativo)',
      etapaAno: '8º ano do Ensino Fundamental II',
      turno: 'Vespertino',
      contatoEscolar: 'Prof. Rodrigo (Orientador Educacional)',
      demandasEscolares: 'Desafios na gestão de tempo com múltiplos professores, planejamento de trabalhos em grupo e organização de cadernos e materiais.',
      adaptacoesApoios: 'Uso de checklist compartilhado no contraturno; permissão para rascunhos em mapas mentais.',
    },
    notasInternas: 'Demonstra excelente raciocínio espacial e repertório verbal refinado. Engaja-se positivamente com estratégias metacognitivas.',
    criadoEm: '2025-08-10',
    atualizadoEm: '2026-03-28',
  },
  {
    id: 'apr-3',
    codigoInterno: 'AP-2025-019',
    nomeCompleto: 'Beatriz Silveira Fontes',
    dataNascimento: '2017-01-15',
    idadeCalculada: 9,
    pronome: 'Ela/Dela',
    contatoPreferencial: '(31) 98234-5678',
    cidadeUf: 'Belo Horizonte/MG',
    status: 'arquivado',
    paisResponsaveis: [
      {
        id: 'resp-4',
        nomeCompleto: 'Fernando Silveira Fontes',
        parentesco: 'Pai',
        responsavelLegal: true,
        telefone: '(31) 98234-5678',
        email: 'fernando.fontes.demo@exemplo.com.br',
        melhorContato: 'Mensagens de texto a qualquer horário',
        autorizacaoConsentimento: {
          status: 'autorizado',
          dataAutorizacao: '2025-03-01',
          observacao: 'Processo concluído com encaminhamento para fonoaudiologia.',
        },
      },
    ],
    contextoEscolar: {
      instituicao: 'Escola Modelo das Paineiras (Demonstrativo)',
      etapaAno: '4º ano do Ensino Fundamental I',
      turno: 'Matutino',
      contatoEscolar: 'Coordenação Pedagógica',
      demandasEscolares: 'Processamento auditivo em ambientes ruidosos e velocidade de cópia do quadro.',
      adaptacoesApoios: 'Material impresso complementar disponibilizado com antecedência.',
    },
    notasInternas: 'Atendimento finalizado em novembro de 2025 após cumprimento dos objetivos de organização e devolutiva completa à escola.',
    criadoEm: '2025-02-28',
    atualizadoEm: '2025-11-30',
  },
];

export const MOCK_SESSOES: Sessao[] = [
  {
    id: 'ses-1',
    aprendenteId: 'apr-2',
    data: '2026-02-03',
    duracaoMinutos: 50,
    modalidade: 'presencial_consultorio',
    local: 'Consultório Principal - Sala A',
    objetivo: 'Investigar recursos de planejamento executivo e organização de rotina semanal.',
    atividades: 'Mapeamento visual da semana escolar utilizando cartões temáticos; introdução à técnica de blocos de estudo com cronômetro visual.',
    comportamentoObservado: 'Acolhedor, atento e comunicativo. Demonstrou cansaço inicial ao falar da matéria de história, mas engajou-se no jogo de classificação.',
    estrategiasEficazes: 'Uso de código de cores para matérias exatas versus humanas; divisão em metas de 15 minutos.',
    dificuldadesEncontradas: 'Dificuldade em estimar o tempo real necessário para redação de textos dissertativos.',
    avancosPercebidos: 'Reconheceu espontaneamente momentos de distração e propôs pausa ativa antes de retomar.',
    orientacoesFamiliaEscola: 'Orientado à mãe não acumular lembretes verbais sucessivos, priorizando o quadro visual no quarto.',
    proximosPassos: 'Experimentar o uso do quadro físico durante os próximos 7 dias e trazer o registro para a próxima sessão.',
    anexos: ['planejamento_semanal_v1.pdf (demonstrativo)'],
    status: 'finalizado',
  },
  {
    id: 'ses-2',
    aprendenteId: 'apr-2',
    data: '2026-02-17',
    duracaoMinutos: 50,
    modalidade: 'presencial_consultorio',
    local: 'Consultório Principal - Sala A',
    objetivo: 'Avaliar a aplicação do quadro de rotina e introduzir estratégias de leitura compreensiva.',
    atividades: 'Revisão das anotações da semana; leitura compartilhada de texto expositivo com identificação de palavras-chave e mapa conceitual.',
    comportamentoObservado: 'Lucas chegou entusiasmado mostrando o quadro preenchido em 4 dos 5 dias úteis.',
    estrategiasEficazes: 'Sublinhar ideias principais com marca-texto amarelo e desenhar símbolos nas margens.',
    dificuldadesEncontradas: 'Tendência a reler parágrafos inteiros quando ocorre perda de foco superficial.',
    avancosPercebidos: 'Maior autonomia na seleção do material necessário antes de iniciar o exercício.',
    orientacoesFamiliaEscola: 'Sugerida validação positiva pela família sobre os 4 dias cumpridos, sem foco punitivo no dia restante.',
    proximosPassos: 'Trabalhar raciocínio lógico-matemático e estratégias de conferência de enunciados.',
    anexos: ['mapa_conceitual_ciencias.png (demonstrativo)'],
    status: 'finalizado',
  },
  {
    id: 'ses-3',
    aprendenteId: 'apr-2',
    data: '2026-03-03',
    duracaoMinutos: 50,
    modalidade: 'presencial_consultorio',
    local: 'Consultório Principal - Sala A',
    objetivo: 'Trabalhar raciocínio lógico-matemático através de jogos com suporte metacognitivo.',
    atividades: 'Jogo de tabuleiro com regras cumulativas (Torre de Hanói adaptada e desafios de frações com material concreto).',
    comportamentoObservado: 'Demonstrou persistência frente a desafios de dificuldade crescente. Verbalizou suas etapas de pensamento espontaneamente.',
    estrategiasEficazes: 'Estimular a autoexplicação antes de movimentar as peças ("O que pretendo alcançar com esse movimento?").',
    dificuldadesEncontradas: 'Impaciência pontual com enunciados com mais de 3 variáveis simultâneas.',
    avancosPercebidos: 'Conseguiu formular uma estratégia alternativa quando o primeiro plano não funcionou, sem desorganização emocional.',
    orientacoesFamiliaEscola: 'Enviada sugestão ao professor de matemática para permitir rascunho de esquemas gráficos na prova.',
    proximosPassos: 'Sessão de devolutiva parcial e alinhamento com a coordenação escolar.',
    anexos: [],
    status: 'finalizado',
  },
  {
    id: 'ses-4',
    aprendenteId: 'apr-2',
    data: '2026-03-17',
    duracaoMinutos: 50,
    modalidade: 'presencial_consultorio',
    local: 'Consultório Principal - Sala A',
    objetivo: 'Consolidação de estratégias de estudo para o período avaliativo do 1º trimestre.',
    atividades: 'Simulação de preparação para prova: auto-interrogação, elaboração de flashcards manuais e teste de retenção.',
    comportamentoObservado: 'Colaborativo, concentrado durante os 40 minutos centrais da sessão.',
    estrategiasEficazes: 'Formulação de perguntas elaboradas pelo próprio aprendente para testar seu conhecimento.',
    dificuldadesEncontradas: 'Resistência a revisar respostas já concluídas antes de entregar.',
    avancosPercebidos: 'Elaborou 12 flashcards de geografia com excelente síntese de conteúdo.',
    orientacoesFamiliaEscola: 'Reforçar pausas de 10 minutos a cada ciclo de 30 minutos em casa.',
    proximosPassos: 'Monitorar os resultados das avaliações escolares e ajustar o plano pedagógico.',
    anexos: ['resumo_flashcards.pdf (demonstrativo)'],
    status: 'revisado',
  },
  {
    id: 'ses-5',
    aprendenteId: 'apr-1',
    data: '2026-02-12',
    duracaoMinutos: 45,
    modalidade: 'presencial_consultorio',
    local: 'Sala de Acolhimento e Brinquedoteca',
    objetivo: 'Sessão lúdica de vínculo e observação inicial da coordenação motora fina e consciência fonológica.',
    atividades: 'Brincadeira de rimas com cantigas de roda; modelagem em massinha de letras do próprio nome; desenho livre.',
    comportamentoObservado: 'Inicialmente reservada, solicitou a presença da mãe nos primeiros 10 minutos. Confortável após o início da atividade de pintura.',
    estrategiasEficazes: 'Músicas ritmadas com palmas para separação silábica.',
    dificuldadesEncontradas: 'Preensão palmar do lápis com pressão excessiva no papel.',
    avancosPercebidos: 'Identificou todas as rimas propostas e nomeou fonemas iniciais das palavras familiares.',
    orientacoesFamiliaEscola: 'Propor em casa brincadeiras de alinhavo e rasgar papel para fortalecimento da musculatura dos dedos.',
    proximosPassos: 'Aplicação de provas operatórias piagetianas e observação psicopedagógica formal.',
    anexos: ['desenho_livre_helena.png (demonstrativo)'],
    status: 'finalizado',
  },
  {
    id: 'ses-6',
    aprendenteId: 'apr-1',
    data: '2026-03-10',
    duracaoMinutos: 45,
    modalidade: 'presencial_consultorio',
    local: 'Sala de Acolhimento e Brinquedoteca',
    objetivo: 'Investigação do nível de conceitualização da escrita (hipóteses de Ferreiro & Teberosky) e provas de conservação.',
    atividades: 'Ditado de 4 palavras e 1 frase da mesma família semântica; prova de conservação de quantidade de matéria (massinha).',
    comportamentoObservado: 'Curiosa e participativa. Apresentou respostas argumentadas nas provas de conservação.',
    estrategiasEficazes: 'Garantir tempo livre de pressa para reflexão antes da escrita.',
    dificuldadesEncontradas: 'Hesitação ao ser confrontada com escrita silábica sem valor sonoro convencional.',
    avancosPercebidos: 'Transição visível da hipótese silábica para silábico-alfabética em palavras de uso frequente.',
    orientacoesFamiliaEscola: 'Orientar a escola a valorizar as produções espontâneas sem correções punitivas à caneta vermelha.',
    proximosPassos: 'Finalizar a redação da síntese diagnóstica compreensiva e agendar devolutiva com pais e professora.',
    anexos: ['prova_escrita_mar26.pdf (demonstrativo)'],
    status: 'rascunho',
  },
];

export const MOCK_EVOLUCAO_DOMINIOS: Record<string, RegistroEvolucaoDominio[]> = {
  'apr-2': [
    {
      dominioId: 'leitura',
      nome: 'Leitura e Compreensão',
      descricaoTextual: 'Evolução da fluência e interpretação de textos expositivos com suporte de palavras-chave.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 2, resumoObservacao: 'Leitura mecânica com perda frequente de sentido em parágrafos longos.' },
        { data: '2025-11-15', nivelObservado: 3, resumoObservacao: 'Início da identificação de conectivos e marcadores temporais.' },
        { data: '2026-01-20', nivelObservado: 3, resumoObservacao: 'Manutenção de estratégias básicas com apoio de marca-texto.' },
        { data: '2026-03-17', nivelObservado: 4, resumoObservacao: 'Capacidade de elaborar resumos e sintetizar ideias principais com boa autonomia.' },
      ],
    },
    {
      dominioId: 'escrita',
      nome: 'Produção Textual e Escrita',
      descricaoTextual: 'Estruturação de parágrafos, coesão textual e planejamento prévio da escrita.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 2, resumoObservacao: 'Frases curtas desconexas e aversão ao rascunho.' },
        { data: '2025-11-15', nivelObservado: 2, resumoObservacao: 'Introdução ao esquema de introdução, desenvolvimento e conclusão.' },
        { data: '2026-01-20', nivelObservado: 3, resumoObservacao: 'Construção de narrativas com encadeamento lógico satisfatório.' },
        { data: '2026-03-17', nivelObservado: 4, resumoObservacao: 'Uso de mapas mentais prévios antes de redigir dissertações escolares.' },
      ],
    },
    {
      dominioId: 'raciocinio',
      nome: 'Raciocínio Lógico-Matemático',
      descricaoTextual: 'Resolução de problemas, compreensão de enunciados e persistência diante de desafios.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 3, resumoObservacao: 'Boa aptidão para cálculo direto, com hesitação na interpretação de enunciados.' },
        { data: '2025-11-15', nivelObservado: 3, resumoObservacao: 'Benefício imediato do destaque visual de incógnitas e dados.' },
        { data: '2026-01-20', nivelObservado: 4, resumoObservacao: 'Avanço na formulação de hipóteses e esquemas gráficos de apoio.' },
        { data: '2026-03-17', nivelObservado: 4, resumoObservacao: 'Resolução confiante de problemas com frações e equações simples.' },
      ],
    },
    {
      dominioId: 'atencao',
      nome: 'Atenção e Autorregulação',
      descricaoTextual: 'Tempo de sustentação do foco e reconhecimento de fadiga cognitiva.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 2, resumoObservacao: 'Sustentação de foco em tarefas individuais por cerca de 10-12 minutos.' },
        { data: '2025-11-15', nivelObservado: 2, resumoObservacao: 'Sensibilidade a estímulos auditivos externos.' },
        { data: '2026-01-20', nivelObservado: 3, resumoObservacao: 'Adoção da técnica Pomodoro adaptada (blocos de 20 minutos).' },
        { data: '2026-03-17', nivelObservado: 4, resumoObservacao: 'Capacidade de autorregular o ambiente e solicitar pausas ativas quando necessário.' },
      ],
    },
    {
      dominioId: 'organizacao',
      nome: 'Organização e Funções Executivas',
      descricaoTextual: 'Planejamento semanal, manuseio de materiais e controle de prazos escolares.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 1, resumoObservacao: 'Esquecimento recorrente de tarefas, cadernos incompletos e perda de prazos.' },
        { data: '2025-11-15', nivelObservado: 2, resumoObservacao: 'Aceitação da rotina visual fixada no quarto com supervisão contínua.' },
        { data: '2026-01-20', nivelObservado: 3, resumoObservacao: 'Utilização autônoma do checklist em 60% dos dias da semana.' },
        { data: '2026-03-17', nivelObservado: 4, resumoObservacao: 'Organização consolidada dos materiais para o dia seguinte sem solicitação externa.' },
      ],
    },
    {
      dominioId: 'comunicacao',
      nome: 'Comunicação e Expressão',
      descricaoTextual: 'Clareza na expressão de dúvidas acadêmicas e interlocução com educadores.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 3, resumoObservacao: 'Comunicação verbal rica, porém com inibição para tirar dúvidas em sala.' },
        { data: '2025-11-15', nivelObservado: 3, resumoObservacao: 'Ensaio de frases-chave para abordagem ao professor no contraturno.' },
        { data: '2026-01-20', nivelObservado: 4, resumoObservacao: 'Proatividade para sinalizar quando não compreendeu um enunciado.' },
        { data: '2026-03-17', nivelObservado: 4, resumoObservacao: 'Participação ativa em debates em grupo com argumentos bem articulados.' },
      ],
    },
    {
      dominioId: 'psicomotricidade',
      nome: 'Habilidades Psicomotoras',
      descricaoTextual: 'Postura de estudo, preensão e coordenação viso-motora.',
      pontos: [
        { data: '2025-09-01', nivelObservado: 4, resumoObservacao: 'Adequado à faixa etária, grafia legível e ritmo confortável.' },
        { data: '2025-11-15', nivelObservado: 4, resumoObservacao: 'Manutenção de ritmo sem fadiga neuromuscular evidente.' },
        { data: '2026-01-20', nivelObservado: 4, resumoObservacao: 'Postura sentada equilibrada com apoio de pés ajustado.' },
        { data: '2026-03-17', nivelObservado: 5, resumoObservacao: 'Excelente coordenação e precisão em representações geométricas manuais.' },
      ],
    },
  ],
};

export const MOCK_ANAMNESES: Record<string, Anamnese> = {
  'apr-1': {
    id: 'ana-1',
    aprendenteId: 'apr-1',
    atualizadoEm: '2026-02-18',
    salvoEm: '2026-02-18T16:45:00Z',
    status: 'revisado',
    motivoProcura: {
      titulo: '1. Motivo da Procura / Encaminhamento',
      relatoFamilia: 'A mãe relata preocupação expressa pela escola quanto ao ritmo de aprendizagem da leitura no início do 2º ano.',
      observacaoProfissional: 'Demanda legítima de escuta e investigação compreensiva sem caráter de urgência patológica.',
      hipoteseTrabalho: 'Necessidade de investigar maturidade das habilidades preditoras de alfabetização e mediação pedagógica recebida.',
    },
    queixaPrincipal: {
      titulo: '2. Queixa Principal e Expectativas',
      relatoFamilia: '"Ela chora quando precisa ler livros da escola e diz que as letrinhas pulam."',
      observacaoProfissional: 'Comportamento de esquiva associado à frustração de expectativas de rendimento perante o grupo.',
      hipoteseTrabalho: 'Desconforto frente a tarefas formais; verificar se há componente de acuidade visual previamente à hipótese psicopedagógica.',
    },
    historiaDesenvolvimento: {
      titulo: '3. História do Desenvolvimento',
      relatoFamilia: 'Desenvolvimento motor no tempo esperado: sentou aos 6 meses, andou com 1 ano e 1 mês.',
      observacaoProfissional: 'Marcos motores globais preservados sem sinais de atraso no relato retrospectivo.',
      hipoteseTrabalho: 'Base sensoriomotora preservada.',
    },
    gestacaoNascimento: {
      titulo: '4. Gestação e Nascimento',
      relatoFamilia: 'Pré-natal sem intercorrências, parto a termo (39 semanas), cesariana planejada. Apgar 9/10.',
      observacaoProfissional: 'Condições perinatais fisiológicas.',
      hipoteseTrabalho: 'Sem fatores de risco gestacionais evidentes.',
    },
    saudeMedicacao: {
      titulo: '5. Saúde e Medicamentos (Dado Sensível)',
      relatoFamilia: 'Alergia respiratória sazonal (rinite). Sem uso contínuo de medicação neurológica ou psiquiátrica.',
      observacaoProfissional: 'Quadro alérgico que demanda atenção quanto à respiração oral e qualidade do sono em períodos de crise.',
      hipoteseTrabalho: 'Impacto potencial na disposição matutina nos dias de crises de rinite.',
    },
    sonoAlimentacaoRotina: {
      titulo: '6. Sono, Alimentação e Rotina',
      relatoFamilia: 'Dorme cerca de 9 horas por noite. Alimenta-se de forma variada com supervisão.',
      observacaoProfissional: 'Rotina de repouso estruturada e favorável à retenção mnêmica.',
      hipoteseTrabalho: 'Fator de proteção presente no ambiente familiar.',
    },
    linguagemComunicacao: {
      titulo: '7. Linguagem e Comunicação',
      relatoFamilia: 'Falou as primeiras palavras por volta de 1 ano. Vocabulário cotidiano rico.',
      observacaoProfissional: 'Boa pragmática e compreensão verbal de ordens compostas.',
      hipoteseTrabalho: 'Competência comunicativa expressiva funcional.',
    },
    aspectosMotores: {
      titulo: '8. Aspectos Motores e Psicomotores',
      relatoFamilia: 'Gosta de andar de patinete e bicicleta com rodinhas. Letra grande que ultrapassa a linha.',
      observacaoProfissional: 'Preensão em transição e necessidade de refinamento no controle da força do traçado.',
      hipoteseTrabalho: 'Necessidade de atividades de estimulação psicomotora fina e esquema corporal.',
    },
    aspectosSocioemocionais: {
      titulo: '9. Aspectos Socioemocionais',
      relatoFamilia: 'Sensível a críticas; muito carinhosa com irmãos menores e animais de estimação.',
      observacaoProfissional: 'Manifesta insegurança perante o erro em situações de testagem; busca confirmação constante do adulto.',
      hipoteseTrabalho: 'Vulnerabilidade à frustração acadêmica; requer acolhimento do erro como etapa construtiva da aprendizagem.',
    },
    trajetoriaEscolar: {
      titulo: '10. Trajetória Escolar',
      relatoFamilia: 'Ingressou na Educação Infantil aos 3 anos. Boa adaptação social, adorava rodas de histórias e teatro.',
      observacaoProfissional: 'Histórico de socialização positivo; a queixa coincidiu com a exigência formal de codificação.',
      hipoteseTrabalho: 'Transição da Educação Infantil para o Fundamental I necessitando de mediação lúdica continuada.',
    },
    leituraEscritaMatematica: {
      titulo: '11. Leitura, Escrita, Matemática e Funções Executivas',
      relatoFamilia: 'Reconhece o alfabeto e números até 20. Conta nos dedos com facilidade.',
      observacaoProfissional: 'Apresenta hipótese silábica com valor sonoro em construção. Bom senso numérico para adições intuitivas.',
      hipoteseTrabalho: 'Processo de alfabetização em curso normal, requerendo consolidação da rota fonológica sem estresse comparativo.',
    },
    relacoesFamiliares: {
      titulo: '12. Relações Familiares e Sociais',
      relatoFamilia: 'Mora com os pais e uma irmã de 3 anos. Avó materna presente na rotina vespertina.',
      observacaoProfissional: 'Ambiente familiar participativo e afetuoso, com disponibilidade para acompanhar orientações.',
      hipoteseTrabalho: 'Rede de apoio familiar estruturada.',
    },
    recursosPotencialidades: {
      titulo: '13. Recursos, Potencialidades e Proteção',
      relatoFamilia: 'Excelente memória para histórias orais, muito criativa nas construções com blocos.',
      observacaoProfissional: 'Capacidade imaginativa rica, persistência em atividades lúdicas de seu interesse.',
      hipoteseTrabalho: 'Utilizar os interesses por narrativas e animais como porta de entrada para a leitura prazerosa.',
    },
    observacoesAdicionais: {
      titulo: '14. Observações Adicionais',
      relatoFamilia: 'Pais manifestam desejo de aprender como apoiar sem criar conflitos na hora da lição de casa.',
      observacaoProfissional: 'Aberto espaço de escuta para orientação parental em devolutiva.',
      hipoteseTrabalho: 'Alívio da sobrecarga emocional nas tarefas domésticas como meta terapêutica prioritária.',
    },
    documentosEncaminhamentos: {
      arquivosDemonstrativos: ['relatorio_escola_ano1.pdf (demonstrativo)', 'exame_audiometrico_normal.pdf (demonstrativo)'],
      anotacoes: 'Exame oftalmológico recente (dezembro de 2025) sem alterações de refração informadas pela mãe.',
    },
  },
};

export const MOCK_AVALIACOES: Record<string, AvaliacaoPsicopedagogica> = {
  'apr-2': {
    id: 'ava-1',
    aprendenteId: 'apr-2',
    perguntaObjetivo: 'Compreender os fatores cognitivos, emocionais e pedagógicos que interferem na autonomia de estudos e organização no 8º ano do Ensino Fundamental.',
    periodoAvaliacao: 'Agosto a Outubro de 2025 (8 sessões diagnósticas)',
    contextoFontes: 'Anamnese com os responsáveis, entrevistas com equipe pedagógica da escola, observação participante e aplicação de provas psicopedagógicas.',
    procedimentosInstrumentos: 'Entrevista Operativa Centrada na Aprendizagem (EOCA), Provas Operatórias Piagetianas, Análise de Cadernos e Provas Escolares, Escala de Autoeficácia Acadêmica.',
    observacoesQualitativas: 'Lucas estabeleceu vínculo cooperativo rápido. Demonstra elevado potencial cognitivo quando não pressionado por tempo restrito. A desorganização é primariamente procedural e não de compreensão.',
    fatoresFacilitadores: 'Excelente repertório linguístico; apoio afetivo familiar constante; bom relacionamento com pares.',
    barreiras: 'Excesso de cobrança interna; falta de métodos explícitos de estudo para matérias com grande carga de leitura.',
    sinteseDescritiva: 'Identificou-se discrepância entre a elevada competência de raciocínio verbal e a baixa consolidação de hábitos de estudo independentes, gerando ansiedade em semanas de provas escolares.',
    recomendacoesPedagogicas: 'Implementação de rotina visual com cronômetro; uso de resumos em fichas; fragmentação de prazos para entregas de trabalhos.',
    encaminhamentos: 'Orientação à escola para envio antecipado do calendário de provas; manutenção de acompanhamento psicopedagógico semanal.',
    limitacoesAvaliacao: 'Processo diagnóstico circumscrito ao contexto pedagógico e relacional do aprendente, não configurando diagnóstico nosológico médico ou neuropsicológico.',
    revisaoProfissional: {
      revisadoPor: 'Dra. Gabriela Antunes (Psicopedagoga Responsável)',
      crpCrppDemonstrativo: 'ABPp 12.345/SP - Demonstrativo',
      dataRevisao: '2025-10-28',
    },
    status: 'finalizado',
  },
};

export const MOCK_RELATORIOS: RelatorioPsicopedagogico[] = [
  {
    id: 'rel-1',
    codigoDocumento: 'REL-2026-004',
    aprendenteId: 'apr-2',
    titulo: 'Relatório Psicopedagógico de Acompanhamento e Evolução Semestral',
    dataCriacao: '2026-03-20',
    dataFinalizacao: '2026-03-25',
    status: 'finalizado',
    secoesAtivas: {
      capa: true,
      identificacaoAprendente: true,
      identificacaoResponsaveis: true,
      demandaMotivo: true,
      periodoContexto: true,
      procedimentosInstrumentos: true,
      antecedentesHistorico: true,
      observacoesProcesso: true,
      perfilAprendizagem: true,
      aspectosObservados: true,
      potencialidadesBarreiras: true,
      sinteseDescritiva: true,
      recomendacoesPraticas: true,
      planoAcompanhamento: true,
      limitacoesEticas: true,
      identificacaoProfissional: true,
    },
    conteudo: {
      demandaMotivo: 'Solicitação da família e da escola para consolidação de estratégias de organização de estudos e transição curricular para o 8º ano do Ensino Fundamental.',
      periodoContexto: 'Período avaliado: de 01/08/2025 a 20/03/2026, compreendendo 18 sessões presenciais no consultório e 2 reuniões de alinhamento com a equipe pedagógica escolar.',
      procedimentosInstrumentos: 'Sessões de intervenção psicopedagógica clínica, análise continuada de materiais didáticos, modelagem de técnicas de estudo (mapas conceituais e auto-interrogação elaborativa) e acompanhamento de rotina semanal.',
      antecedentesHistorico: 'Lucas iniciou acompanhamento após notar-se que, apesar de excelente raciocínio em sala, apresentava queixas frequentes de sobrecarga e esquecimento de tarefas com a multiplicação de disciplinas.',
      observacoesProcesso: 'Ao longo do ciclo, observou-se notável redução da resistência inicial ao planejamento escrito. Lucas passou a ser protagonista de suas escolhas de horário e demonstra satisfação ao verificar suas metas cumpridas.',
      perfilAprendizagem: 'Predileção por abordagens conceituais ricas em significado e debates orais. Dificuldade atenuada na conversão de pensamentos complexos em textos estruturados.',
      aspectosObservados: 'Atenção sustentada aumentada para 35 minutos em tarefas complexas. Funções executivas em franca maturação com o suporte do quadro visual.',
      potencialidadesBarreiras: 'Potencialidades: Criatividade, curiosidade intelectual e capacidade reflexiva. Barreiras atuais: Gerenciamento de tarefas em grupo em que depende do ritmo de colegas.',
      sinteseDescritiva: 'O aprendente demonstrou evolução significativa em sua postura metacognitiva, evoluindo de uma atitude reativa para uma postura de antecipação e autocuidado com seus compromissos escolares.',
      recomendacoesFamilia: 'Manter a celebração dos progressos de autonomia; preservar os momentos de lazer no fim de semana sem pauta de estudos; manter o diálogo aberto sobre sentimentos relacionados à escola.',
      recomendacoesEscola: 'Continuar disponibilizando o cronograma de trabalhos com antecedência mínima de 10 dias úteis; estimular o papel de liderança em discussões conceituais em sala.',
      planoAcompanhamento: 'Manutenção de sessões quinzenais para acompanhamento da transição para o 2º trimestre escolar, com revisão agendada para junho de 2026.',
      limitacoesEticas: 'Este relatório baseia-se em observações psicopedagógicas do processo de aprendizagem e destina-se exclusivamente ao suporte pedagógico e familiar do aprendente, não devendo ser utilizado para fins periciais ou estigmatizantes.',
      identificacaoProfissional: {
        nome: 'Dra. Gabriela Antunes Ferreira',
        registroProfissional: 'Psicopedagoga Clínica - ABPp nº 14.892/SP',
        instituicaoConsultorio: 'Espaço Integrado de Desenvolvimento e Aprendizagem',
        cidadeData: 'São Paulo, 25 de Março de 2026',
      },
    },
  },
  {
    id: 'rel-2',
    codigoDocumento: 'REL-2026-002',
    aprendenteId: 'apr-1',
    titulo: 'Parecer Psicopedagógico Inicial e Devolutiva Escolar',
    dataCriacao: '2026-03-12',
    status: 'em_revisao',
    secoesAtivas: {
      capa: true,
      identificacaoAprendente: true,
      identificacaoResponsaveis: true,
      demandaMotivo: true,
      periodoContexto: true,
      procedimentosInstrumentos: true,
      antecedentesHistorico: true,
      observacoesProcesso: true,
      perfilAprendizagem: true,
      aspectosObservados: true,
      potencialidadesBarreiras: true,
      sinteseDescritiva: true,
      recomendacoesPraticas: true,
      planoAcompanhamento: true,
      limitacoesEticas: true,
      identificacaoProfissional: true,
    },
    conteudo: {
      demandaMotivo: 'Investigação do processo de alfabetização inicial e apoio nas adaptações didáticas para o 2º ano do Ensino Fundamental.',
      periodoContexto: 'Fevereiro a Março de 2026. Quatro encontros presenciais de avaliação e anamnese aprofundada com os pais.',
      procedimentosInstrumentos: 'Avaliação da consciência fonológica, provas piagetianas de seriação e classificação, escrita de palavras e desenho livre.',
      antecedentesHistorico: 'Desenvolvimento global dentro do esperado; insegurança manifestada perante cobranças formais de escrita no ambiente escolar.',
      observacoesProcesso: 'Helena responde com entusiasmo a estímulos lúdicos, cantigas e histórias compartilhadas.',
      perfilAprendizagem: 'Canal de entrada preferencialmente auditivo e cinestésico; necessidade de contextualização concreta dos fonemas.',
      aspectosObservados: 'Hipótese silábico-alfabética em consolidação; discriminação fonêmica preservada; motricidade fina necessitando de relaxamento muscular.',
      potencialidadesBarreiras: 'Potencial criativo elevado e ambiente familiar acolhedor; barreira: autocrítica exacerbada diante do erro gráfico.',
      sinteseDescritiva: 'Constata-se processo de alfabetização em curso com ritmo próprio e saudável, beneficiando-se de reforço de autoestima e propostas lúdicas.',
      recomendacoesFamilia: 'Ler histórias diariamente sem cobrar que a criança leia; propor jogos de rima e adivinhações.',
      recomendacoesEscola: 'Adotar pauta com linha guia ampliada; evitar comparações de rendimento; incentivar a escrita livre espontânea.',
      planoAcompanhamento: 'Ciclo inicial de 12 sessões semanais focado em jogos psicopedagógicos de consciência fonológica.',
      limitacoesEticas: 'Documento demonstrativo confidencial gerado para mediação educacional.',
      identificacaoProfissional: {
        nome: 'Dra. Gabriela Antunes Ferreira',
        registroProfissional: 'Psicopedagoga Clínica - ABPp nº 14.892/SP',
        instituicaoConsultorio: 'Espaço Integrado de Desenvolvimento e Aprendizagem',
        cidadeData: 'São Paulo, 12 de Março de 2026',
      },
    },
  },
  {
    id: 'rel-3',
    codigoDocumento: 'REL-2026-001',
    aprendenteId: 'apr-1',
    titulo: 'Rascunho de Devolutiva Prévia de Anamnese',
    dataCriacao: '2026-02-20',
    status: 'rascunho',
    secoesAtivas: {
      capa: false,
      identificacaoAprendente: true,
      identificacaoResponsaveis: true,
      demandaMotivo: true,
      periodoContexto: false,
      procedimentosInstrumentos: false,
      antecedentesHistorico: true,
      observacoesProcesso: false,
      perfilAprendizagem: false,
      aspectosObservados: false,
      potencialidadesBarreiras: true,
      sinteseDescritiva: true,
      recomendacoesPraticas: true,
      planoAcompanhamento: false,
      limitacoesEticas: true,
      identificacaoProfissional: true,
    },
    conteudo: {
      demandaMotivo: 'Síntese preliminar dos dados colhidos na anamnese de 10/02/2026.',
      periodoContexto: 'Fevereiro de 2026.',
      procedimentosInstrumentos: 'Escuta clínica de anamnese com genitores.',
      antecedentesHistorico: 'Marcos de desenvolvimento típicos; rinite alérgica pontual.',
      observacoesProcesso: 'Genitores muito cooperativos e comprometidos com o bem-estar da filha.',
      perfilAprendizagem: 'A ser investigado nas sessões lúdicas.',
      aspectosObservados: 'Aguardando encerramento das provas operatórias.',
      potencialidadesBarreiras: 'Apoio afetivo excelente.',
      sinteseDescritiva: 'Rascunho preliminar para orientar o plano de trabalho diagnóstico.',
      recomendacoesFamilia: 'Manter a rotina de sono e evitar comentários sobre o rendimento escolar na frente da criança.',
      recomendacoesEscola: 'Aguardar devolutiva completa antes de intervenções especializadas externas.',
      planoAcompanhamento: 'Proposta de 4 sessões diagnósticas.',
      limitacoesEticas: 'Rascunho interno profissional para reflexão clínica.',
      identificacaoProfissional: {
        nome: 'Dra. Gabriela Antunes Ferreira',
        registroProfissional: 'ABPp nº 14.892/SP',
        instituicaoConsultorio: 'Espaço Integrado',
        cidadeData: 'São Paulo, Fevereiro de 2026',
      },
    },
  },
  {
    id: 'rel-4',
    codigoDocumento: 'REL-2025-019',
    aprendenteId: 'apr-3',
    titulo: 'Relatório Psicopedagógico de Conclusão de Atendimento (Arquivado)',
    dataCriacao: '2025-11-20',
    dataFinalizacao: '2025-11-28',
    status: 'arquivado',
    secoesAtivas: {
      capa: true,
      identificacaoAprendente: true,
      identificacaoResponsaveis: true,
      demandaMotivo: true,
      periodoContexto: true,
      procedimentosInstrumentos: true,
      antecedentesHistorico: true,
      observacoesProcesso: true,
      perfilAprendizagem: true,
      aspectosObservados: true,
      potencialidadesBarreiras: true,
      sinteseDescritiva: true,
      recomendacoesPraticas: true,
      planoAcompanhamento: true,
      limitacoesEticas: true,
      identificacaoProfissional: true,
    },
    conteudo: {
      demandaMotivo: 'Conclusão dos objetivos psicopedagógicos estabelecidos para o ano letivo de 2025.',
      periodoContexto: 'Março a Novembro de 2025.',
      procedimentosInstrumentos: 'Atendimentos semanais e articulação com a equipe escolar e fonoaudiológica.',
      antecedentesHistorico: 'Dificuldades de atenção seletiva em ambientes ruidosos e lentidão na cópia do quadro.',
      observacoesProcesso: 'Excelente resposta às adaptações de posicionamento em sala de aula e apoio fonoaudiológico concomitante.',
      perfilAprendizagem: 'Pensamento analítico aguçado com consolidação de estratégias de auto-organização.',
      aspectosObservados: 'Avanço expressivo na autonomia para estudos e recuperação do ritmo de cópia.',
      potencialidadesBarreiras: 'Barreiras superadas satisfatoriamente no ambiente de 4º ano.',
      sinteseDescritiva: 'Objetivos de intervenção alcançados com êxito. Devolutiva final realizada para família e coordenação em 28/11/2025.',
      recomendacoesFamilia: 'Manter incentivo à leitura literária nas férias e hábitos saudáveis de sono.',
      recomendacoesEscola: 'Manter a aprendente posicionada nas primeiras carteiras da fileira central.',
      planoAcompanhamento: 'Alta psicopedagógica com previsão de contato preventivo no início do 5º ano se necessário.',
      limitacoesEticas: 'Documento demonstrativo de encerramento clínico.',
      identificacaoProfissional: {
        nome: 'Dra. Gabriela Antunes Ferreira',
        registroProfissional: 'ABPp nº 14.892/SP',
        instituicaoConsultorio: 'Espaço Integrado',
        cidadeData: 'Belo Horizonte, Novembro de 2025',
      },
    },
  },
];

export const MOCK_MODELOS_FORMULARIOS: ModeloFormulario[] = [
  {
    id: 'mod-anamnese',
    titulo: 'Anamnese Psicopedagógica Completa',
    categoria: 'anamnese',
    descricao: 'Roteiro compreensivo em 15 seções recolhíveis, separando relatos da família de observações técnicas do profissional.',
    indicacaoUso: 'Primeiras consultas com os responsáveis antes ou no início do processo diagnóstico.',
    itensEstimados: 15,
    tempoMedioPreenchimentoMinutos: 45,
  },
  {
    id: 'mod-sessao',
    titulo: 'Registro de Sessão Psicopedagógica',
    categoria: 'sessao',
    descricao: 'Registro estruturado de objetivos, atividades realizadas, comportamentos observados, estratégias e orientações.',
    indicacaoUso: 'Ao final de cada atendimento clínico ou institucional para rastreabilidade.',
    itensEstimados: 10,
    tempoMedioPreenchimentoMinutos: 15,
  },
  {
    id: 'mod-avaliacao',
    titulo: 'Síntese de Avaliação Psicopedagógica',
    categoria: 'avaliacao',
    descricao: 'Instrumento para consolidar evidências qualitativas observadas por domínios sem geração automática de diagnósticos.',
    indicacaoUso: 'Conclusão de ciclos diagnósticos ou marcos semestrais de acompanhamento.',
    itensEstimados: 12,
    tempoMedioPreenchimentoMinutos: 35,
  },
  {
    id: 'mod-escolar',
    titulo: 'Formulário de Acompanhamento e Contato Escolar',
    categoria: 'escolar',
    descricao: 'Coleta padronizada de informações pedagógicas com coordenadores, professores e mediadores.',
    indicacaoUso: 'Visitas escolares, reuniões pedagógicas e acompanhamento de adaptações curriculares.',
    itensEstimados: 8,
    tempoMedioPreenchimentoMinutos: 20,
  },
  {
    id: 'mod-devolutiva',
    titulo: 'Roteiro de Devolutiva à Família',
    categoria: 'devolutiva',
    descricao: 'Estrutura empática para apresentação oral de achados, potencialidades e orientações sem termos patologizantes.',
    indicacaoUso: 'Sessão final de devolutiva diagnóstica e renovação de planos.',
    itensEstimados: 7,
    tempoMedioPreenchimentoMinutos: 25,
  },
  {
    id: 'mod-plano',
    titulo: 'Plano de Intervenção e Metas Psicopedagógicas',
    categoria: 'plano',
    descricao: 'Definição de objetivos de curto, médio e longo prazo com indicadores observáveis e revisão periódica.',
    indicacaoUso: 'Início do ciclo de intervenção continuada.',
    itensEstimados: 6,
    tempoMedioPreenchimentoMinutos: 30,
  },
];

// Today's date calculation for realistic appointments
const hoje = new Date();
const pad = (n: number) => n.toString().padStart(2, '0');
const dataHojeStr = `${hoje.getFullYear()}-${pad(hoje.getMonth() + 1)}-${pad(hoje.getDate())}`;

const amanha = new Date(hoje);
amanha.setDate(amanha.getDate() + 1);
const dataAmanhaStr = `${amanha.getFullYear()}-${pad(amanha.getMonth() + 1)}-${pad(amanha.getDate())}`;

const ontem = new Date(hoje);
ontem.setDate(ontem.getDate() - 1);
const dataOntemStr = `${ontem.getFullYear()}-${pad(ontem.getMonth() + 1)}-${pad(ontem.getDate())}`;

export const MOCK_LEMBRETES: LembreteConsulta[] = [
  {
    id: 'lem-1',
    aprendenteId: 'apr-2',
    nomeAprendente: 'Lucas Mendes Vasconcelos',
    tipoCompromisso: 'sessao_individual',
    data: dataHojeStr,
    horarioInicio: '14:30',
    duracaoMinutos: 50,
    fusoHorario: 'America/Sao_Paulo (GMT-3)',
    modalidade: 'presencial',
    local: 'Consultório Principal - Sala A',
    observacoes: 'Trazer mapas conceituais de ciências e o cronograma do 2º trimestre.',
    recorrencia: 'semanal',
    alertasAntecedencia: [1440, 60, 15], // 1 dia, 1 hora e 15 minutos antes
    status: 'agendado',
  },
  {
    id: 'lem-2',
    aprendenteId: 'apr-1',
    nomeAprendente: 'Helena Duarte Ribeiro',
    tipoCompromisso: 'devolutiva_pais',
    data: dataAmanhaStr,
    horarioInicio: '10:00',
    duracaoMinutos: 60,
    fusoHorario: 'America/Sao_Paulo (GMT-3)',
    modalidade: 'presencial',
    local: 'Sala de Atendimento aos Pais',
    observacoes: 'Devolutiva da avaliação inicial com presença de Mariana e Carlos. Apresentação do plano lúdico.',
    recorrencia: 'nenhuma',
    alertasAntecedencia: [1440, 120, 30],
    status: 'agendado',
  },
  {
    id: 'lem-3',
    aprendenteId: 'apr-1',
    nomeAprendente: 'Helena Duarte Ribeiro',
    tipoCompromisso: 'reuniao_escola',
    data: dataHojeStr,
    horarioInicio: '17:00',
    duracaoMinutos: 45,
    fusoHorario: 'America/Sao_Paulo (GMT-3)',
    modalidade: 'online',
    local: 'Videoconferência com Coordenação Pedagógica',
    observacoes: 'Alinhamento sobre as fichas visuais de leitura com a professora Tatiana.',
    recorrencia: 'nenhuma',
    alertasAntecedencia: [30, 5],
    status: 'agendado',
  },
  {
    id: 'lem-4',
    aprendenteId: 'apr-3',
    nomeAprendente: 'Beatriz Silveira Fontes',
    tipoCompromisso: 'sessao_individual',
    data: dataOntemStr,
    horarioInicio: '09:00',
    duracaoMinutos: 50,
    fusoHorario: 'America/Sao_Paulo (GMT-3)',
    modalidade: 'presencial',
    local: 'Consultório Principal - Sala B',
    observacoes: 'Sessão demonstrativa arquivada.',
    recorrencia: 'nenhuma',
    alertasAntecedencia: [60],
    status: 'concluido',
  },
];
